### ISSUE TITLE
dequeue failed for scq

### ISSUE THREAD

**Issue by d-wang03** [rusnikola/lfqueue#3]
I write a simple case to use scq, using the data structures in scq.h, just enqueue a value and then dequeue it.
However, the dequeued value is LFRING_EMPTY.
I'm running it on Intel Core i5 12500, with gcc 11.3 as compiler, under Ubuntu 22.04.
my code is show below:
`
#define SCQ_ORDER 15U
#define EMPTY (void *) LFRING_EMPTY
typedef struct _queue_t {
  char ring[LFRING_SIZE(SCQ_ORDER)];
} queue_t __attribute__((aligned(128)));

static inline void enqueue(queue_t * q, void * val)
{
  size_t eidx = (size_t) val;
  lfring_enqueue((struct lfring *) q->ring, SCQ_ORDER, eidx, false);
}

static inline void * dequeue(queue_t * q)
{
  return (void *) lfring_dequeue((struct lfring *) q->ring, SCQ_ORDER, false);
}

int main()
{
    int32_t value = 100;
    queue_t free_list = {0};
    lfring_init_empty((struct lfring *) free_list.ring, SCQ_ORDER);
    enqueue(&free_list, &value);
    int32_t* pval = dequeue(&free_list);
    if (pval == &value && *pval == value)
        printf("OK\n");
    return 0;
}
`

**Comment by d-wang03** [comment]
maybe the calculation of cycle is not suitable?
in dequeue(), the ecycle == hcycle is never meet.

**Comment by rusnikola** [comment]
@d-wang03 Thanks for your interest in lfqueue. No, this example is incorrect.

1. First of all, I assume you have lfring * cast in lfring_init_empty and then int32_t *pval = dequeue(...)
2. The problem here is that you cast an arbitrary 64-bit pointer and then attempt to squeeze it in inside eidx. That breaks the queue because eidx cannot exceed the maximum queue size - 1. (To optimize performance, eidx is *assumed* to not violate this requirement but it is never enforced; so if you insert something wrong, it will just silently damage the queue.) If you want to use arbitrary pointers, you need to use scqd or scq2 rather than scq.
3. To fix your particular example, you can do something like this:
enqueue(&free_list, (void *) 100);
instead of
enqueue(&free_list, &value);

and then check that the dequeue returns (void *) 100.
